name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Trigger Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Send Trigger
      run: |
        curl -X POST "${{ secrets.CF_PAGES_TRIGGER }}"
