name: Deploy Assets to R2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Remove source files
      working-directory: content
      run: |
        find . -name "*.haml" -type f -delete

    - name: Sync to R2
      uses: skymins04/r2-dir-upload@0.0.0.1
      with:
        accountid: ${{ secrets.CF_ACCOUNT_ID }}
        accesskeyid: ${{ secrets.CF_ACCESS_KEY }}
        secretaccesskey: ${{ secrets.CF_SECRET_KEY }}
        bucket: ${{ secrets.CF_R2_BUCKET }}
        source: ${{ github.workspace }}/content
        destination: /
